version: '3'

services:
  ansible-control:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: ansible-control
    volumes:
      - ./cp-ansible:/ansible/ansible_collections/confluent/platform:rw
      - ./inventories:/ansible/inventories
      - ./share:/usr/share/cp-ansible-sandbox
    environment:
      - ANSIBLE_GATHERING=smart
      - ANSIBLE_HOST_KEY_CHECKING=False
      - ANSIBLE_RETRY_FILES_ENABLED=False
      - ANSIBLE_COLLECTIONS_PATH=/ansible/ansible_collections
      - ANSIBLE_SSH_PIPELINING=True
      - ANSIBLE_INVENTORY=/ansible/inventories/ansible-inventory.yml

  # Build inventory node image ONCE and reuse for all nodes
  zookeeper1:
    image: inventory-node:24.04
    build:
      context: .
      dockerfile: Dockerfile-inventory-node
    hostname: zookeeper1
    privileged: true
    cap_add:
      - ALL
    ports:
      - "2222:22"
    volumes:
      - ./share:/usr/share/cp-ansible-sandbox
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run/lock
      - /run
      - /tmp
    environment:
      - DEBIAN_FRONTEND=non-interactive

  zookeeper2:
    image: inventory-node:24.04
    hostname: zookeeper2
    privileged: true
    cap_add:
      - ALL
    ports:
      - "2223:22"
    volumes:
      - ./share:/usr/share/cp-ansible-sandbox
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run/lock
      - /run
      - /tmp
    environment:
      - DEBIAN_FRONTEND=non-interactive

  zookeeper3:
    image: inventory-node:24.04
    hostname: zookeeper3
    privileged: true
    cap_add:
      - ALL
    ports:
      - "2224:22"
    volumes:
      - ./share:/usr/share/cp-ansible-sandbox
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run/lock
      - /run
      - /tmp
    environment:
      - DEBIAN_FRONTEND=non-interactive

  kafka1:
    image: inventory-node:24.04
    hostname: kafka1
    privileged: true
    cap_add:
      - ALL
    ports:
      - "2225:22"
    volumes:
      - ./share:/usr/share/cp-ansible-sandbox
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run/lock
      - /run
      - /tmp
    environment:
      - DEBIAN_FRONTEND=non-interactive

  kafka2:
    image: inventory-node:24.04
    hostname: kafka2
    privileged: true
    cap_add:
      - ALL
    ports:
      - "2226:22"
    volumes:
      - ./share:/usr/share/cp-ansible-sandbox
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run/lock
      - /run
      - /tmp
    environment:
      - DEBIAN_FRONTEND=non-interactive

  kafka3:
    image: inventory-node:24.04
    hostname: kafka3
    privileged: true
    cap_add:
      - ALL
    ports:
      - "2227:22"
    volumes:
      - ./share:/usr/share/cp-ansible-sandbox
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run/lock
      - /run
      - /tmp
    environment:
      - DEBIAN_FRONTEND=non-interactive

  connect:
    image: inventory-node:24.04
    hostname: connect
    privileged: true
    cap_add:
      - ALL
    ports:
      - "2229:22"
    volumes:
      - ./share:/usr/share/cp-ansible-sandbox
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run/lock
      - /run
      - /tmp
    environment:
      - DEBIAN_FRONTEND=non-interactive

  schema-registry:
    image: inventory-node:24.04
    hostname: schema-registry
    privileged: true
    cap_add:
      - ALL
    ports:
      - "2230:22"
    volumes:
      - ./share:/usr/share/cp-ansible-sandbox
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run/lock
      - /run
      - /tmp
    environment:
      - DEBIAN_FRONTEND=non-interactive

  ksqldb:
    image: inventory-node:24.04
    hostname: ksql
    privileged: true
    cap_add:
      - ALL
    ports:
      - "2231:22"
    volumes:
      - ./share:/usr/share/cp-ansible-sandbox
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run/lock
      - /run
      - /tmp
    environment:
      - DEBIAN_FRONTEND=non-interactive

  control-center:
    image: inventory-node:24.04
    hostname: control-center
    privileged: true
    cap_add:
      - ALL
    ports:
      - "2228:22"
      - "9021:9021"
    volumes:
      - ./share:/usr/share/cp-ansible-sandbox
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run/lock
      - /run
      - /tmp:exec,mode=777
    environment:
      - DEBIAN_FRONTEND=non-interactive
